# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a26dd9e15c413338dd77b8f6fb08212"
name = "smart-returns-app"
handle = "smart-returns-app"
application_url = "https://home-reads-attorney-da.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_orders, write_orders, read_customers"

[auth]
redirect_urls = ["https://home-reads-attorney-da.trycloudflare.com/auth/callback", "https://home-reads-attorney-da.trycloudflare.com/auth/shopify/callback", "https://home-reads-attorney-da.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
